Pocket/list-api

.docker/mysql/schema/schema.sql, schema.graphql, src/dataService/listPaginationService.ts, src/dataService/savedItemsService.ts, src/test/functional/queryServices.test/savedItems-filters.integration.ts, src/types/index.ts
Update `contentType` filter per https://github.com/Pocket/spec/pull/134
Jira ticket: INFRA-367
=> feat(filters): update contentType filters

src/dataService/listPaginationService.ts
Drop temp tables if they exist before creating them.
The root cause is unclear since the temp tables are dropped after use. Dropping them before creating ensures that we don't hit this issue.
Sentry: https://sentry.io/organizations/pocket/issues/3084150129/?project=5761820&query=is%3Aunresolved
=> fix(temp tables): Ensure temp tables do not exist before creating

.circleci/continue-config.yml, lambda/batchDelete/index.ts, lambda/events/index.ts
Fix file path
Jira ticket: INFRA-567
=> fix: fix invalid packaged lambda file path

.circleci/config.yml, .circleci/continue-config.yml
=> fix(ci): conditional build working and parameter fix

.docker/mysql/schema/schema.sql, package-lock.json, package.json, src/dataService/savedItemsService.ts, src/server/main.ts, src/server/routes/batchDelete.ts, src/test/functional/mutationServices.test/savedItemsMutationService-delete.integration.ts, src/test/http/batchDelete.spec.ts
Add basic batchDelete REST endpoint with schema validation.
- the structure 
- Use modular routes
- Use express-validator to enforce contract
- Include a trace ID for log analysis
- Don't keep http connection open waiting for promise to resolve -- just kick off the transaction and return a 'gotchu' response
- errors sent to cloudwatch/sentry asynchronously
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-571
=> feat(batchDelete): add batch delete endpoint

.aws/src/SqsLambda.ts, .circleci/continue-config.yml, jest.config.js, lambda/batchDelete/config.ts, lambda/batchDelete/index.spec.ts, lambda/batchDelete/index.ts, lambda/batchDelete/jest.config.js, lambda/batchDelete/jest.setup.js, lambda/batchDelete/package-lock.json, lambda/batchDelete/package.json, lambda/batchDelete/tsconfig.json, src/server/routes/batchDelete.spec.ts
Add lambda code for invoking batchDelete endpoint on List API, through SQS message batches
Reports partial failures/successes.
- any
- Spec tests only for this, e2e has diminishing returns
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-569
=> feat(batchDelete): batchDelete lambda handler

.aws/src/main.ts
Fix queue IAM
Jira ticket: INFRA-619
=> fix(IAM): fix batch delete queue IAM

src/server/routes/queueDelete.ts, src/test/integration/queueDelete.integration.ts
Update request validation to replace `status` with `isPremium`
Jira ticket: INFRA-621
=> fix(validation): update request validation

lambda/events/handlers/accountDelete.spec.ts, lambda/events/handlers/accountDelete.ts, src/server/routes/queueDelete.ts
Change `status` to `isPremium`
Jira ticket: INFRA-624
=> fix(sqs message): change status to isPremium

.aws/src/lambda/base/SqsLambda.ts
add ReportBatchItemFailures to FunctionResponseTypes
=> fix(lambda): add ReportBatchItemFailures to FunctionResponseTypes

src/server/routes/queueDelete.ts
=> fix(account delete): offset calculation

.aws/package-lock.json, .aws/package.json, .aws/src/main.ts
Only notify #log-backend-deploys on a failed deployment
=> fix(notifications): only on failed

src/config/index.ts
Temporarily raise page size for iOS testing.
Let's wait til Monday to push this.
=> fix: temporarily raise page size for testing

src/aws/batchDeleteHandler.spec.ts, src/config/index.ts
list-api - batch delete 20 messages every 30 seconds.
as per discussion from dev-QA testing.
=> fix: reduce batch size to 20; and batch frequency to 30 sec

.aws/src/main.ts
=> Revert "fix: task count set to 1 for now"

src/dataService/tagDataService.ts
Update comments for clarity
Follow-up from #534
=> fix: update comments for clarity

docker-compose.yml
Finer-grained dependency management
=> fix(deps): pin localstack sha

src/config/index.ts
chore: delete 100 records every 10 seconds
=> chore: delete 100 records every 10 seconds

src/config/index.ts
- read 1000 records. 
- chunk them into 500 records per message. delete 500 records every 2 secs
=> chore: delete 500 every 2 secs

src/aws/batchDeleteHandler.spec.ts, src/config/index.ts
reduce polling from 30 seconds to 5 seconds (still should be good considering out ms query performance time)
=> chore: reduce polling from 30 seconds to 5 seconds

src/aws/batchDeleteHandler.spec.ts, src/config/index.ts, src/dataService/savedItemsService.ts
fix: db query to use whereIn tp see if it fixes sentry error
=> fix: db query to use whereIn tp see if it fixes sentry error

src/aws/batchDeleteHandler.spec.ts, src/config/index.ts
db load is too low - so deciding to reduce the polling delay to increase deletion rate
=> chore: reduce polling delay back to 2 secs; reduce process sleep to 500ms

.aws/src/main.ts, src/config/index.ts
chore: making error percentage as critical alert for list-api
=> chore: making error percentage as critical alert for list-api

src/database/client.ts
Reduce connection timeout to 6 seconds.
=> fix(db): reduce connection timeout to 6s

src/server/routes/queueDelete.ts
fix: remove email check as we dont have emails for historically deleted users
=> fix: remove email check as we dont have emails for historically deleted users

buildspec.yml
trying to fix dev environment code build
code build successful: https://us-east-1.console.aws.amazon.com/codesuite/codebuild/410318598490/projects/ListAPI-Dev/history?region=us-east-1&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ
=> fix(dev env): trying to fix dev environment code build 

.aws/package-lock.json, .aws/package.json, .aws/src/lambda/EventLambda.ts, .aws/src/lambda/base/SqsLambda.ts, .aws/src/main.ts, .circleci/config.yml, Dockerfile, docker-compose.yml, package-lock.json, package.json
What changed? What is the business/product goal?
- Change 1
- Change 2
- 
- 
> Write a #changelog message using our [best practices](https://docs.google.com/document/d/1oEt8Mtkp-6Xz9S2zaNX1EIXfQIEDN2JpY0diuPc1HZc/edit) if this PR (potentially) impacts users. Describe the 'why' and 'what'. @mention relevant teams. Link to this PR.
Jira ticket:
* https://getpocket.atlassian.net/browse/BACK-
Documentation:
* Project doc
=> Update tf modules

.aws/package-lock.json, .aws/package.json, .aws/src/lambda/EventLambda.ts, .aws/src/lambda/base/SqsLambda.ts, .aws/src/main.ts
Update terraform modules version used. This picks up pagerduty service timeout changes.
=> feat(pagerduty): extend pagerduty svc ack timeout via tf modules update

schema.graphql, src/resolvers/index.ts
This PR only contains the gql schema update for **INFRA-818.** Implementation will follow in another PR.
=> feat(saveUpsert): [INFRA-818] Add schema update for saveUpsert only

.circleci/config.yml, docker-compose.yml, package-lock.json, package.json, schema.graphql, src/server/apollo.ts, src/server/buildSchema.ts, src/server/schema.ts
Add constraint directives to list-api schema.
- Update federation version and imports
- Add constraint directive and compose
- Update server to include constraint defs in schema
- Update build process to generate schema in /dist (build folder)
- Update circleci to use generated schema
- any
- generate schema in /dist (build folder)
=> feat(constraint): add constraint directive

src/database/client.ts
Disable our replication pooling for writes.
=> fix(pooling): disabling connection pooling

schema.graphql, src/businessEvents/itemsEventEmitter.spec.ts, src/businessEvents/unifiedEventKinesisHandler.spec.ts, src/dataLoader/savedItemsDataLoader.spec.ts, src/resolvers/index.ts, src/server/context.spec.ts, src/test/graphql/mutations/savedItemsMutationService-upsert.integration.ts, src/test/graphql/queries/item.integration.ts, src/test/graphql/queries/pocketSave-item.integration.ts, src/test/graphql/queries/savedItem.integration.ts, src/test/graphql/queries/savedItems.integration.ts, src/test/graphql/queries/tags.integration.ts, src/test/integrations/eventBridge.integration.ts, src/test/integrations/snowplowHandler.integration.ts, src/types/index.ts
=> Revert "feat(federation): resolve Item by itemId"

schema.graphql, src/dataService/savedItemsService.ts, src/models/SavedItem.ts, src/resolvers/index.ts, src/resolvers/mutation.ts, src/test/graphql/mutations/savedItem/savedItemUnDelete.integration.ts
To support offline mobile clients. Continuing patterns from #801, #802, etc.
[IN-1474]
[IN-1474]: https://getpocket.atlassian.net/browse/IN-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(undelete): undelete by url

schema.graphql, src/businessEvents/itemsEventEmitter.spec.ts, src/businessEvents/unifiedEventKinesisHandler.spec.ts, src/dataLoader/savedItemsDataLoader.spec.ts, src/resolvers/index.ts, src/server/context.spec.ts, src/test/graphql/mutations/savedItemsMutationService-upsert.integration.ts, src/test/graphql/queries/item.integration.ts, src/test/graphql/queries/savedItem.integration.ts, src/test/graphql/queries/savedItems.integration.ts, src/test/graphql/queries/tags.integration.ts, src/test/integrations/eventBridge.integration.ts, src/test/integrations/snowplowHandler.integration.ts, src/types/index.ts
=> Revert "INFRA-1324: removing @shareable directive from Item itemId & resolving Item by itemId"

.aws/src/main.ts
Scaling ECS task back post iOS next release. After reviewing resource utilization it would make sense to increase the task size to better handle spikey loads, and decrease task count to save money.
Jira ticket:
- https://mozilla-hub.atlassian.net/browse/POC-206
=> chore(scaling): increase task size, decrease min/max task count

src/dataService/savedItemsService.ts, src/test/graphql/mutations/savedItemsMutationService-delete.integration.ts
This code has been subsumed by AccountDataDeleter.
=> chore: remove unused batchDelete code
