Dockerfile

This updates the `From` node image we are using to one with many less
vulnerabilities.
```
Base Image             Vulnerabilities  Severity
node:16.13.1-bullseye  171              6 critical, 11 high, 29 medium,
125 low
Recommendations for base image upgrade:
Alternative image types
Base Image                  Vulnerabilities  Severity
node:current-slim           37               1 critical, 2 high, 0
medium, 34 low
node:16.13.1-bullseye-slim  37               1 critical, 2 high, 0
medium, 34 low
node:17.0-buster-slim       62               2 critical, 11 high, 5
medium, 44 low
node:17.3.0-buster          370              3 critical, 37 high, 67
medium, 263 low
```
What changed? What is the business/product goal?
- Updating the from image. I noticed this looking through the Amazon …

chore(Dockerfile) Update image

---

src/config/index.ts
src/dataService/queryServices/savedItemsService.ts
src/dataService/queryServices/tagDataService.ts
src/resolvers/user.ts
src/resolvers/utils.spec.ts
src/resolvers/utils.ts
src/types/index.ts

validate pagination for combination
- first
- first/after
- last
- last/after
- restricted to the max first/last limit to 100. this way, we can restrict large db read at once..
Jira ticket:
https://getpocket.atlassian.net/browse/INFRA-2

feat(pagination): validating pagination inputs to receive first alone, last alone or the combination of {after, first} and {before,last}.

---

src/dataLoader/savedItemsDataLoader.ts
src/server/context.spec.ts
src/server/context.ts

We should make a dataloader for each new request (each time the context is created). Subsequent calls to the dataloader on the same context object should return the same dataloader object. This fixes a bug where a new dataloader was created every time the property was accessed (resulting in no actual batch/cache).
Also adds a small optimization to fill both SavedItem loader caches when one is accessed (loading by ID/Url fills both loader caches)
* Fill dataloader cache of alternate key when one is accessed (i.e. loading a SavedItem by ID fills the cache for SavedItem by url)
[INFRA-258]
[INFRA-258]: https://getpocket.atlassian.net/browse/INFRA-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: reuse dataloaders within same request context

---

src/dataService/queryServices/savedItemsService.ts
src/test/functional/queryServices.test/savedItems-filters.integration.ts

Only use non-deleted highlights (status=1) for `isHighlighted` filter
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-310

fix(SavedItemsFilter): only use active highlights for isHighlighted

---

package-lock.json
package.json
src/dataService/listPaginationService.ts
src/test/functional/queryServices.test/savedItems-filters.integration.ts

Quick bugfix for a bug I found where an error was thrown if the filter did not return any results (due to attempting to access a field on an undefined object).
- Add test to capture case
- Update to pass test

bugfix(savedItems): do not throw error if filter returns no result

---

.docker/mysql/schema/schema.sql
src/test/functional/mutationServices.test/savedItemsMutationService-delete.integration.ts
src/test/functional/mutationServices.test/tagsMutationService-update.integration.ts

Ensure sinon fake timer is only installed once in tests.
`sinon.useFakeTimers` was being called more than once individual integration tests.
Root cause: sinon was bumped to version 13.x from 12.x
Jira ticket: INFRA-440

fix(tests): ensure sinon fake timer is only installed once in tests

---

schema.graphql
src/dataService/listPaginationService.ts
src/dataService/savedItemsService.ts
src/dataService/tagDataService.ts
src/dataService/usersMetaService.ts
src/resolvers/index.spec.ts
src/resolvers/index.ts
src/resolvers/item.ts
src/resolvers/mutation.ts
src/server/apolloServer.ts
src/server/context.spec.ts
src/server/context.ts
src/test/functional/mutationServices.test/savedItemsMutationService-delete.integration.ts
src/test/functional/mutationServices.test/savedItemsMutationService-updates.integration.ts
src/test/functional/mutationServices.test/savedItemsMutationService-upsert.integration.ts
src/test/functional/mutationServices.test/tagsMutationService-create.integration.ts
src/test/functional/mutationServices.test/tagsMutationService-delete.integration.ts
src/test/functional/mutationServices.test/tagsMutationService-update.integration.ts
src/test/functional/mutationServices.test/tagsMutationService-updateSavedItemTags.integration.ts
src/test/functional/mutationServices.test/usersMetaService.integration.ts
src/test/functional/queryServices.test/pagination-benchmarking.integration.ts
src/test/functional/queryServices.test/savedItem.integration.ts
src/test/functional/queryServices.test/savedItems-filters.integration.ts
src/test/functional/queryServices.test/savedItems.integration.ts
src/test/functional/queryServices.test/tags-sadpath.integration.ts
src/test/functional/queryServices.test/tags.integration.ts
src/test/functional/testServerUtil.ts
src/test/integration/savedItemsService.integration.ts

Use a consistent db connection (read / write) throughout the resolver chain for a given request.
For example, for the following mutation: 
```graphql
mutation CreateTags {
createSavedItemTags({ savedItemId: 1, tags: ["this", "one"]}) {
id
tags {
name  
}
}
}
```
`tags` is not resolved as part of the saved item, but through a separate resolver in the chain. In the original design, this would mean that the `tags` resolver will use a read db connection. The problem with using a read db connection after a mutation is that we lose strong consistency in the response to the client due to replication lag. 
The work in this PR ensures that for a mutation, every downstream resolver, uses the same connection i.e. the write db connection that was used to perform the mutation. This way we have a true …

feat(mutations): set db connection to write for all mutations

---

src/dataService/listPaginationService.ts
src/test/functional/queryServices.test/savedItems-archive-pagination.integration.ts

Fixes a bug where the wrong mapping was used
to map sortBy to the key in the response,
causing cursor date to be undefined.
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-447

fix: cursor generation

---

schema.graphql
src/dataService/tagDataService.ts
src/resolvers/index.ts
src/resolvers/mutation.ts
src/test/functional/mutationServices.test/tagsMutationService-replaceSavedItemTags.integration.ts
src/types/index.ts

Implement replaceSavedItemTags per https://github.com/Pocket/spec/blob/main/source/client-api/list/schema.graphql.
Related spec PR: https://github.com/Pocket/spec/pull/143
- Implementation
- Reused existing code for deleting and creating tags
Jira ticket: INFRA-437

feat(tags): implement replaceSavedItemTags mutation

---

schema.graphql
src/resolvers/mutation.ts
src/test/functional/mutationServices.test/tagsMutationService-delete.integration.ts

update `deleteSavedItemTags` to return a `SavedItem` array instead of `SavedItemTagAssociation` (per https://github.com/Pocket/spec/blob/main/source/client-api/list/schema.graphql)
- 
- small spec update to not allow nulls in the response at all
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-438

feat(tags): update deleteSavedItemTags response

---

src/businessEvents/itemsEventEmitter.spec.ts
src/businessEvents/sqs/transformers/index.ts
src/businessEvents/types.ts
src/businessEvents/unifiedEventKinesisHandler.spec.ts
src/server/context.ts
src/test/functional/mutationServices.test/savedItemsMutationService-upsert.integration.ts

Only send message to the permanent library queue if user is premium
Jira ticket: INFRA-574

fix(SQS): only premium users get Perm Lib

---

src/config/index.ts
src/dataService/savedItemsService.ts
src/test/functional/queryServices.test/savedItem.integration.ts

- Limit pagination maximum to 30
- Correctly use `time_read` as `archivedAt` in the `SavedItem` entity
Jira ticket: INFRA-582

fix(bug): return time_read as archivedAt

---

.aws/src/lambda/BatchDeleteLambda.ts
.aws/src/lambda/base/SqsLambda.ts

Limit lambda concurrency to avoid db overload

fix: limit lambda concurrency for deleter

---

src/config/index.ts

Reduce batch size of list deletes (number of rows deleted per message) to 100, selecting 500 at a time.

chore: reduce queue delete batch size

---

.aws/package.json
.aws/src/main.ts
src/config/index.ts

Increase sqs visibility timeout so the messages don't reappear in the queue quickly. we do this coz some deletion queries run upto 1000s.
increase message retention time to 14 days (max allowed)
set task count to 1 as this app is used by beta client only for now.. 
move the batchDeleteHandler to its own ecs task. so we can scale it down to 1 without affecting the API scaling in a future PR - https://getpocket.atlassian.net/browse/INFRA-662

fix: increase sqs visibility config and retention time

---

.aws/src/main.ts

Revert task count as `list` tables doesn't have any longer queries from testing.

fix: Revert task count

---

src/config/index.ts
src/dataService/savedItemsService.ts
src/test/functional/mutationServices.test/savedItemsMutationService-delete.integration.ts

from testing we observed that mysql sometimes does table-scan instead of delete by primary key index for batch deletes.
so we now delete one row at a time from list related tables 
- delete one row per table based on itemId
- removed transactions as the deletes are un-related and we want to delete max row possible, and the transcation shouldn't hold a session for a longer time
- sleep for 20 secs before the next delete, to reduce the replication lags in read replicas
slack conversation: https://pocket.slack.com/archives/C03E28D1GUD/p1658190886666469?thread_ts=1658187746.380859&cid=C03E28D1GUD

fix: delete one row at a time from list-tables

---

.aws/src/main.ts

- setting task count to 1 for deletion test in production. we will scale it back up once the metrics look good in prod.
- right now, the app is used by beta iOS clients, and web clients behind a feature flag.

fix: task count set to 1 for now

---

src/dataService/savedItemsService.ts

remove item_session; moving it to account-data-deleter to delete the rows by PK `id`. this table doesn't have the composite index (user_id, item_id)

fix: remove item_session; moving it to account-data-deleter

---

src/dataService/tagDataService.ts

Use groupBy for more reliable ordering than distinct.

fix(suggestedTags): use groupBy for more reliable ordering than distinct

---

src/dataService/tagDataService.ts

I couldn't get the tests to fail, which is why I didn't update them...
This should solve the issue with inconsistent dates.

fix(suggestedTags): aggregate function order by (max timestamp)

---

src/config/index.ts

if the cpu load is still under 50%, we can look to batch delete 50 records every 10 secs
Ticket: https://getpocket.atlassian.net/browse/INFRA-779

chore: batch delete 50 records every 10 seconds

---

src/config/index.ts

delete 100 records every 5 seconds
cpu load is at ~41%
the RAM memory is low
the read latency is also low (1.25 ms)
https://us-east-1.console.aws.amazon.com/rds/home?region=us-east-1#database:id=pocket-db-primary-0-prod-cluster;is-cluster=true;tab=monitoring

chore: delete 100 records every 5 seconds

---

src/config/index.ts

chore: delete 200 records every 3 secs
Reasoning:
- db load: ~45%
- latency: ~1.25 ms
- freeable memory still at ~48k MB
- performance insight queries: most expensive query time is ~100-200ms, so sleep time 3 sec is well above the time required for the table lock to release

chore: delete 200 records every 3 secs

---

src/aws/batchDeleteHandler.spec.ts
src/config/index.ts

total delay between deletes (1 sec polling delay + 0.5 secs sleep)
db load is at ~10%
we can probably let it run seeing how things are going 
slack thread: https://pocket.slack.com/archives/C03QVL4SU/p1668620128626459?thread_ts=1668618924.659309&cid=C03QVL4SU

fix: reducing to 1 sec and reducing batch size to 250.

---

src/businessEvents/sqs/transformers/index.ts
src/config/index.ts

chore: add breadcrumbs to check if any specific action fails
checked all mutations. all savedItem mutation actually passes a resolved savedItem. the tag-savedItem association mutations are the one that passes the promise, but the test seem to have covered these getSavedItemById functions.
so adding breadcrumbs to see if there is a specific event that's giving us this error (or) happens randomly for all events
for error: https://sentry.io/organizations/pocket/issues/3464752853/?project=5761820&referrer=project-issue-stream
ticket: https://getpocket.atlassian.net/browse/INFRA-804

chore: add breadcrumbs to check if any specific action fails

---

src/database/client.ts

Testing out increasing the max connection pool. Do not merge until tomorrow.
The current limit on connections is 5000 based on our RDS instance types.
`SHOW GLOBAL VARIABLES LIKE 'max_connections`

fix(db): increase max connection pool size

---

src/aws/batchDeleteHandler.spec.ts
src/aws/batchDeleteHandler.ts
src/config/index.ts
src/dataService/savedItemsService.ts

Earlier we paused deletion of list-items as we were seeing increase in db load in replicas, and this was caused due to increase in metric `RollbackSegmentHistoryListLength`
Recent investigations by SRE team shows feed-machine queries were causing high HLL, so we are re-activating the deletion pipeline in list-api
https://pocket.slack.com/archives/C01CLPFMJJ1/p1670435709030319
https://pocket.slack.com/archives/C01CLPFMJJ1/p1670446585409359

chore: bring back account deletion

---

src/server/main.ts

Expose a health check url so blue-green deployment works. Apollo server removed health check. We can update to do a trivial query but this requires less code update and fits with previous patterns ([annotations-api](https://github.com/Pocket/annotations-api/blob/d45cf157e7191aa04024ab5b47faff5a7c070e43/src/server/index.ts#L42))
[INFRA-842]
[INFRA-842]: https://getpocket.atlassian.net/browse/INFRA-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: expose health check url

---

schema.graphql
src/resolvers/index.ts
src/test/graphql/queries/curatedItem.integration.ts
src/test/graphql/queries/item.integration.ts

Clients need to know if a Corpus Item has been saved to a user's saves for display purposes. (ie. should they display a saved button on recomendations)

feat(corpusItem): adding in savedItem on corpus item

---

schema.graphql
src/dataService/index.ts
src/dataService/pocketSavesService.spec.ts
src/dataService/pocketSavesService.ts
src/dataService/tagDataService.ts
src/dataService/utils.spec.ts
src/dataService/utils.ts
src/models/index.ts
src/models/pocketSave.spec.ts
src/models/pocketSave.ts
src/models/tag.spec.ts
src/models/tag.ts
src/resolvers/index.ts
src/server/context.ts
src/test/graphql/queries/pocketSave.integration.ts
src/types/index.ts

This PR adds the first pass as a PocketSave entity, which is scheduled to eventually replace SavedItem.
To make the split easier, PocketSave has largely used code separated from SavedItem.
It's also been setup to follow a proposed new pattern where business logic lives in models, data source / database logic lives in dataservice, and resolvers are as dumb as possible.
- getting date handling for 0000-00-00 00:00:00 was a real pain in the ass, since the value coming from the knex response sometimes would be a Date object returning NaN, other times it would be a string. Probably should move the existing checks into utils, but would appreciate other eyes & thoughts
- this is a new setup, would appreciate feedback on it
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-821

feat(PocketSave): Create a PocketSave entity that is retrievable by ID for now

---

schema.graphql
src/resolvers/index.ts
src/test/graphql/queries/pocketSave.integration.ts

Adding the bulk mutation responses from the accepted proposal so that implementing tickets don't have to deal with mege conflicts.
Also includes a fix to `pocketSaveById -> saveById` to comply with accepted proposal.
[INFRA-811]
[INFRA-811]: https://getpocket.atlassian.net/browse/INFRA-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating schema for bulk mutation responses

---

package-lock.json
src/resolvers/index.ts

~blocked by #643~
Update ISOString type to actually point to the custom scalar definition from apollo-utils package.
- should I add more date tests here as well?
- mostly upstream
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-812

feat(isostring): use isostring custom scalar

---

schema.graphql
src/models/item.spec.ts
src/models/item.ts
src/models/pocketSave.spec.ts
src/models/pocketSave.ts
src/resolvers/index.ts
src/resolvers/savedItem.ts
src/server/context.ts
src/test/graphql/mutations/savedItemsMutationService-upsert.integration.ts
src/test/graphql/queries/pocketSave-item.integration.ts
src/types/index.ts

Add itemId to Item and PendingItem
- Resolve the type with the __typename field we already provide from the Item resolver function
- Add ItemModel with method for resolving an Item on a PocketSave
- Use fed2 directives because itemId is now `@shareable` on Item
~Edit: Need a little work to get the schema to compose after the fed2 move, but all other code is ready~ Fixed
- Including on PocketResource
- I added the item field to PocketSave, although it will be superseded by `resource` according to the contract. I can remove it if we want.
[INFRA-1040]
[INFRA-1040]: https://getpocket.atlassian.net/browse/INFRA-1040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(PendingItem): add itemId to pending item

---

src/test/graphql/queries/pocketSave-tags.integration.ts

Resolve tags on PocketSave.
Turns out that @cmharlow had already implemented this feature! This just adds integration testing to close the loop. 
[INFRA-483]
[INFRA-483]: https://getpocket.atlassian.net/browse/INFRA-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(tags): add integration tests for resolving tags on PocketSave

---

schema.graphql
src/dataService/pocketSavesService.ts
src/models/pocketSave.ts
src/resolvers/index.ts
src/test/graphql/mutations/save-unfavorite.integration.ts
tsconfig.json

Adds a mutation to unfavorite a PocketSave entity.
Does not add emission of events yet given separate discussion that moved that to another ticket.
i was half tempted to simply add a 'favorite/unfavorite' argument to the existing favoriteListRow && saveFavorite methods, but decided to go more explicit (and verbose). but not opposed to merging these however.
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-546

feat(unfave): ability to unfavorite a pocketsave

---

docker-compose.yml
schema.graphql
src/dataService/pocketSavesService.ts
src/models/pocketSave.ts
src/resolvers/index.ts
src/test/graphql/mutations/save-unarchive.integration.ts

Add ability to unarchive a PocketSave or list of PocketSaves.
Also set the app TZ for the docker-compose setup to US/Central as well, as it was showing errors running locally (undesired timezone shifts). See impl notes for more details on this.
- again, the main push of this PR is just copy & pasting & altering with a 'un' the archive stuff already existing, but i'm open to cutting down on verbosity & just adding on/off arguments to existing functions
- i did investigate whether or not we could get away from forcing all app servers using this code to be in the same TZ (system-wide) by using the MySQL package ConnectionConfig.timezone option. Unfortunately, it just doesn't work with negative offsets. Plus with this route, we'd have to manage DST changes ourselves. It  would obviate the …

feat(unarchive): ability to unarchive a pocketsave

---

.circleci/scripts/setup_aws.sh
package.json
schema.graphql
src/dataService/savedItemsService.ts
src/resolvers/mutation.ts
src/test/graphql/mutations/savedItemsMutationService-upsert.integration.ts
src/types/index.ts

Adding support for the `title` field for the `upsertSavedItem` mutation.
We can now provide `title` as part of the mutation input. If provided in the input it will be saved and returned. 
If not provided as part of the mutation input, will be set to what the parser call returns and saved as that.
Jira ticket:
* https://getpocket.atlassian.net/browse/INFRA-1195

feat(upsertSavedItem): [INFRA-1195] Add title field to upsertSavedItem mutation

---

.circleci/config.yml

This is so it can be picked up for Docker image build and thus be in runtime dir so the server will start (because of /src/server/typeDefs.ts).
Fixes bug introduced by #717

bug(schema.graphql): re-add schema.graphql file to workspace

---

.circleci/config.yml
.circleci/continue-config.yml

Add job step failure notifications. Uses post-steps in circleci to notify on failure of any step. Since the branch filtering is applied to main only, I didn't apply to any steps not run on main.
Tested on previous (reverted) commit using build pass notification to ensure that the integration was properly set up. 
- any
- use post-steps to hook into each workflow job
Documentation:
* [Project doc](https://getpocket.atlassian.net/wiki/spaces/PE/pages/2950857054/Circleci+Slack+Deployment+Notifications)

feat(ci): circleci slack notification on failed job steps

---

schema.graphql

Adding additional "payload" types to use bulk mutations under the SavedItem namespace
- Deleting incomplete saves work from schema? (not necessarily removing fully from codebase)
Jira ticket:
* [IN-1408]
[IN-1408]: https://getpocket.atlassian.net/browse/IN-1408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(schema): payload types 'save' -> 'savedItem'namespace [IN-1408]

---

.aws/src/lambda/EventLambda.ts
Dockerfile

**this is part 1:**
with i-os going live and there is a possibility of ECS task auto-scaling, we don't want our background process account-deletion to scale up with ECS
so we are moving account deletion from this repo to account-data-deleter: https://github.com/Pocket/account-data-deleter/pull/354
- removed the subscription for `user-events`. this would make sure the account-deletion pipeline will not process any user-events from event-bridge
`  # aws_sns_topic_subscription.listapi_sqseventconsumer_usereventssnssubscription_0ADA249B will be destroyed`
`  # aws_sqs_queue.listapi_sqseventconsumer_usereventssnssubscription_snstopicdql_333CF5B8 will be destroyed`
`  # aws_sqs_queue_policy.listapi_sqseventconsumer_usereventssnssubscription_snsdlqpolicy_9D972253 will be destroyed`
`  # …

chore(account-deletion): remove user-events subscription (for account-deletion)

---

package-lock.json
package.json
src/server/apollo.ts

This PR includes two quick fixes. The first leverages work already done (just updates the apollo-utils package version so it gets used). The second change was a recommendation that came out of an incident retro due to Apollo changing their default masking behavior. 
- Bump apollo-utils package version to automatically tag Sentry errors with x-graph-request-id header
passed from gateway.
- Disable masking from Apollo Studio inline trace reporting; send all errors unmodified to dev, and ~do not send common user-driven errors to prod (UNAUTHENTICATED, NOT_FOUND, BAD_USER_INPUT~) _edit: send all errors to prod for now._
Ticket: [IN-1467]
This change has been deployed to dev successfully, and the apollo engine is healthy (confirmed with some trivial manual queries).
[IN-1467]: …

fix(observability): Quick Fixes

---

schema.graphql
src/dataService/tagDataService.ts
src/externalCaller/parserCaller.spec.ts
src/externalCaller/parserCaller.ts
src/models/tag.ts
src/resolvers/index.ts
src/test/graphql/mutations/savedItemTag.integration.ts
src/test/utils/parserMocks.ts
src/types/index.ts

Resolve issues with offline mobile clients by enabling tagging by givenUrl. Other mutations/queries will follow. This is because givenUrl is available offline, but a server-provided itemId (which is the key for accessing all saves at this time), is not available for offline clients creating new saves.
- is the parser dependency ok for a short term solution?
- failing with NOT_FOUND if parser does not have an itemId for url (vs. using createIfNone param)
- Use the parser for resolving itemId instead of replicating the url transformation/hashing logic and looking up in `readitla_b` from list
- alternatively also, use the parser instead of looking up by givenUrl in `list` since givenUrl is not indexed (request has been made to index this field)
- do not create the itemId if it doesn't exist; …

feat(tags): enable tagging by givenUrl

---

jest.config.js
package-lock.json
package.json
src/config/index.ts
src/dataService/savedItemsService.ts
src/dataService/tagDataService.ts
src/test/graphql/mutations/tagsMutationService-update.integration.ts

If 'where in' array is too large, then
mysql will ignore indices and scan the
entire table. The exact value at which
this happens depends on some memory settings.
Manual testing showed that 10k size will work
(we can tune this with the config value in
the future).

fix(db): chunk queries to avoid full table scan

---

schema.graphql
src/businessEvents/itemsEventEmitter.spec.ts
src/businessEvents/unifiedEventKinesisHandler.spec.ts
src/dataLoader/savedItemsDataLoader.spec.ts
src/resolvers/index.ts
src/server/context.spec.ts
src/test/graphql/mutations/savedItemsMutationService-upsert.integration.ts
src/test/graphql/queries/item.integration.ts
src/test/graphql/queries/pocketSave-item.integration.ts
src/test/graphql/queries/savedItem.integration.ts
src/test/graphql/queries/savedItems.integration.ts
src/test/graphql/queries/tags.integration.ts
src/test/integrations/eventBridge.integration.ts
src/test/integrations/snowplowHandler.integration.ts
src/types/index.ts

Use item_id to federate Item instead of givenUrl. This is safer and more reliable due to the vagaries of URL encoding and whatnot...
See [slack](https://pocket.slack.com/archives/C03QVL4SU/p1684867901864509) for more context

feat(federation): resolve Item by itemId

---

schema.graphql
src/dataService/savedItemsService.ts
src/models/SavedItem.ts
src/resolvers/index.ts
src/resolvers/mutation.ts
src/test/graphql/mutations/savedItem/savedItemFavorite.integration.ts
src/test/graphql/mutations/savedItem/savedItemUnFavorite.integration.ts

Add mutation to favorite/unfavorite by url identifier, to support offline mobile clients.
Extends the same pattern as #801
- Continuing the same pattern as archive/unarchive in #801 
Jira ticket:
* [IN-1473]
* [IN-1471]
[IN-1473]: https://getpocket.atlassian.net/browse/IN-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IN-1471]: https://getpocket.atlassian.net/browse/IN-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(favorite/unfavorite): un/favorite by givenUrl

---

schema.graphql
src/dataService/savedItemsService.ts
src/models/SavedItem.ts
src/resolvers/index.ts
src/resolvers/mutation.ts
src/test/graphql/mutations/savedItem/savedItemDelete.integration.ts
src/test/integrations/savedItemsService.integration.ts

Add mutation to delete a SavedItem by url. Continuing on the theme from #801 and #802
- any
- putting non-user-facing delete tests on the data service integration test vs. bundling with the graphql e2e tests
Jira ticket:
* [IN-1475]
[IN-1475]: https://getpocket.atlassian.net/browse/IN-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(delete): delete a SavedItem by url

---

.aws/src/config/index.ts

send events to the shared event bus. [successfully pushed to dev](https://app.circleci.com/pipelines/github/Pocket/list-api/5598/workflows/bc883721-876c-4aba-9c23-2f69a8c10705).
anything else we need to check here?
Jira ticket:
* https://getpocket.atlassian.net/browse/OSL-549

fix(event bus): send to shared event bus (instead of default)

---

schema.graphql

- mark `savedItem.title` as alpha as its not resolved yet
- mark them as deprecated as we will use it only for third party clients API (v3 proxy work). internal clients are expected to use `item.title`

chore(savedItem.title): deprecate savedItem.title in schema docs

---

schema.graphql
src/test/graphql/queries/pocketSave-item.integration.ts

Removing `itemId` from the extended `Item` type as it does not get resolved and is not a key. Fixing integration tests.
Already have tested this change doesn't break anything by directly pushing up the client schema changes to prod
Jira ticket:
* [https://getpocket.atlassian.net/browse/INFRA-1324](https://getpocket.atlassian.net/browse/INFRA-1324)

INFRA-1324: remove itemId from extended Item type

---

src/businessEvents/eventBatchProcessor.spec.ts

Skip a test that's been flaky for a while. The risk of losing this coverage is very low because it's for a system that is no longer used in production.
Goal is to get PRs merged easier.

chore(test): skip flaky test
